# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    files_directory: '%kernel.project_dir%/public/uploads/product/files'
    bills_directory: '%kernel.project_dir%/public/uploads/product/bills'
    devis_directory: '%kernel.project_dir%/public/uploads/product/devis'
    email: 'lgauthier@akatraductions.com'
    base_url : 'https://api.stripe.com'
    stripe_pk_test: 'pk_test_W2lQqUZ0BHapP3fyYddX35DJ009ZFdfKJt'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Service\FileService:
        arguments:
            $files_directory: '%files_directory%'
            $bills_directory: '%bills_directory%'
            $devis_directory: '%devis_directory%'

    App\Service\MailService:
        arguments:
            $email: '%email%'

    App\Service\StripeService:
        arguments:
            $baseUrl: '%base_url%'
            $pkTest: '%stripe_pk_test%'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
